export default  {
    products:[
        {
        _id: '1',
        name : 'Slime Shirt',
        Category:'Shirt',
        image : '/images/d1.jpg',
        price : 60,
        brand: 'Nike',
        rating:4.5,
        numReviews:4.5,
        countInStock: 6,
    },
    {
        _id: '2',
        name : 'Best Shirt',
        Category:'Shirt',
        image : '/images/d1.jpg',
        price : 75,
        brand: 'Nike',
        rating:3.5,
        numReviews:3.5,
        countInStock: 6,
    },
    {
        _id: '3',
        name : 'Fit Pant',
        Category:'Pant',
        image : '/images/d1.jpg',
        price : 80,
        brand: 'Nike',
        rating:2.5,
        numReviews:10,
        countInStock: 6,
    },
    {
        _id: '4',
        name : 'Fit Pant',
        Category:'Pant',
        image : '/images/d1.jpg',
        price : 80,
        brand: 'Nike',
        rating:1.5,
        numReviews:10,
        countInStock: 6,
    },
    {
        _id: '5',
        name : 'Fit Pant',
        Category:'Pant',
        image : '/images/d1.jpg',
        price : 80,
        brand: 'Nike',
        rating:1.5,
        numReviews:10,
        countInStock: 6,
    }
]
}